name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git submodule update --init --recursive
      - name: Build project and run tests
        run: ./gradlew build --stacktrace

  test_installation:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git submodule update --init --recursive
      - run: ./gradlew assemble executableAsJar --stacktrace
      - run: unzip -d ./unzipped ./cli/build/libs/protodata.jar
      - name: Prepare installation dir
        run: mkdir $HOME/application
      - run: ./unzipped/install.sh $HOME/application
      - name: Launch ProtoData
        run: source $HOME/.bash_profile && protodata -h

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git submodule update --init --recursive
      - name: Publish artifacts to Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish --stacktrace -x test
