name: Build under Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace

      # See: https://github.com/marketplace/actions/junit-report-action
      - name: Publish Unit Test Report
        uses: mikepenz/action-junit-report@v3.5.2
        if: always() # always run even if the previous step fails
        with:
          check_name: Regular Unit Tests
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true # will fail workflow if test reports not found

      # See: https://github.com/marketplace/actions/junit-report-action
      - name: Publish Functional Test Report
        uses: mikepenz/action-junit-report@v3.5.2
        if: always() # always run even if the previous step fails
        with:
          check_name: Functional Tests
          report_paths: 'gradle-plugin/build/test-results/functionalTest/TEST-*.xml'
          require_tests: true # will fail workflow if test reports not found

      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
