name: Installation on Ubuntu

on: push

jobs:
  test:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Build artifacts
        run: ./gradlew assemble setupJar --stacktrace

      - name: Extract installation materials from an archive
        run: unzip -d ./unzipped ./cli/build/libs/protodata.jar

      - name: Prepare installation dir
        run: mkdir $HOME/application

      - name: Install ProtoData
        run: ./unzipped/install.sh $HOME/application

      - name: Launch ProtoData
        run: source $HOME/.bash_profile && protodata -h
