name: Build

on:
  push:
#    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: git submodule update --init --recursive
      - name: Publish artifacts to Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew assemble publish --stacktrace
